In [1]:
from langchain_ollama import OllamaLLM
from typing_extensions import TypedDict
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langgraph.graph import StateGraph, START, END
from db_create import CargaDeArchivos
import re

In [2]:
a= CargaDeArchivos()
a.run_carga()
db_conn= a.conn


class State(TypedDict):
    """
    Represents the state of the workflow, including the question, schema, database connection,
    relevance, SQL query, query result, and other metadata.
    """
    question: str
    schema: str
    db_conn: None
    relevance: str
    sql_query: str
    query_result: str
    sql_error: bool
    final_answer: str
    attempts: int

In [11]:
def convert_nl_to_sql(state: State):
    """
    Converts a natural language question into an SQL query based on the database schema.

    Args:
        state (State): The current state of the workflow.
        config (RunnableConfig): Configuration for the runnable.

    Returns:
        State: Updated state with the generated SQL query.
    """
    question = state["question"]
    print(f"Converting question to SQL {question}")
    system = """
    You are an SQL assistant specialized in DuckDB. Your task is to generate accurate SQL queries based on natural language questions, following the provided schema.

    ### Database Schema  
    #### Table: "cases"
    - "id" (VARCHAR): Primary key.
    - "insurance" (BIGINT): Foreign key to insurance.
    - "avg_time" (DOUBLE): Duration (seconds) from case initiation to closure.
    - "type" (VARCHAR): Insurance category.
    - "branch" (VARCHAR): Policy branch.
    - "ramo" (VARCHAR): Coverage type.
    - "broker" (VARCHAR): Broker for the policy.
    - "state" (VARCHAR): Current case state.
    - "client" (VARCHAR): Client who bought the insurance.
    - "creator" (VARCHAR): Employee managing the case.
    - "value" (BIGINT): Insurance monetary value.
    - "approved" (BOOLEAN): TRUE if approved, else FALSE.
    - "insurance_creation" (TIMESTAMP_NS): Policy creation timestamp.
    - "insurance_start" (TIMESTAMP_NS): Coverage start timestamp.
    - "insurance_end" (TIMESTAMP_NS): Coverage end timestamp.

    #### Table: "activity"
    - "id" (BIGINT): Primary key.
    - "case" (VARCHAR): Foreign key to "cases"."id".
    - "timestamp" (TIMESTAMP_NS): Activity timestamp.
    - "name" (VARCHAR): Name of the activity.
    - "case_index" (BIGINT): Alias for "id".
    - "tpt" (DOUBLE): Activity duration (seconds).

    ### Query Guidelines  
    1. **Use Table Aliases**: "cases" → c, "activity" → a.
    2. **Always Reference Columns with Aliases**: c."id", a."case".
    3. **Handle Aggregations**: Include non-aggregated columns in GROUP BY.
    4. **Date & Time Calculations**: Use EXTRACT(DAY FROM ...) for durations.
    5. **Filtering Conditions**: Use TRUE/FALSE for boolean values.
    6. **Use Explicit Joins**: Avoid implicit joins.
    7. **Optimize for Performance**: Use indexes, avoid unnecessary calculations, and limit results when needed.
    8. **Restrict Queries to Existing Tables**: Only use "cases" and "activity" tables.

    ### Output Format  
    - Return only the SQL query, with no extra formatting.  
    - Do **NOT** include language tags like `sql`, `vbnet`, or any other markers.  
    """



    llm= OllamaLLM(model="sqlcoder:latest",temperature="0.0")
    
    convert_prompt = ChatPromptTemplate.from_messages(
        [
            ("system", system),
            ("human", "Question: {question}"),
        ]
    )
    sql_generator = convert_prompt | llm
    result = sql_generator.invoke({"question": question})
    message= re.sub(r"^\s*SQL:\s*", "", result, flags=re.IGNORECASE).strip()
    state["sql_query"] = message
    print(f"Generated SQL query: {state['sql_query']}")
    return state


def execute_sql(state:State):
    """
    Executes the SQL query on the  database and retrieves the results.

    Args:
        state (State): The current state of the workflow.
        config (RunnableConfig): Configuration for the runnable.

    Returns:
        State: Updated state with the query results or error information.
    """
    sql_query = state["sql_query"].strip()
    db_conn = state["db_conn"]  
    print(f"Executing SQL query: {sql_query}")

    try:
        # Ensure the query targets only the allowed tables
        allowed_tables = ["cases", "activity"]
        if not any(table in sql_query.lower() for table in allowed_tables):
            raise ValueError(f"Query must target only the tables: {', '.join(allowed_tables)}.")

        # Execute the SQL query using the connection
        cursor = db_conn.cursor()
        cursor.execute(sql_query)

        # Fetch results if it's a SELECT query
        if sql_query.lower().startswith("select"):
            rows = cursor.fetchall()
            columns = [desc[0] for desc in cursor.description]

            # Format the output
            if rows:
                formatted_result = "\n".join(
                    ", ".join(f"{col}: {row[idx]}" for idx, col in enumerate(columns))
                    for row in rows
                )
                print("SQL SELECT query executed successfully.")
            else:
                formatted_result = "No results found."
                print("SQL SELECT query executed successfully but returned no rows.")

            state["query_rows"] = rows
        else:
            formatted_result = "The action has been successfully completed."
            print("SQL command executed successfully.")

        state["query_result"] = formatted_result
        state["sql_error"] = False

    except Exception as e:
        state["query_result"] = f"Error executing SQL query: {str(e)}"
        state["sql_error"] = True
        print(f"Error executing SQL query: {str(e)}")
    print(state['query_result'])
    return state

In [12]:
test_cases = [
    {"question": "How many cases are there in total in the database?",
    "expected_sql": 'SELECT COUNT(*) FROM cases;'},
    {"question": "How many activities have been recorded?",
    "expected_sql": 'SELECT COUNT(*) FROM activity;'},
    {"question": "What are the different types of insurance available?",
    "expected_sql": 'SELECT DISTINCT type FROM cases;'},
    {"question": "What is the total value of approved insurance policies?",
    "expected_sql": 'SELECT SUM(value) FROM cases WHERE approved = 1;'},
    {"question": "How many cases were created in January?",
    "expected_sql": 'SELECT COUNT(*) FROM cases WHERE EXTRACT(MONTH FROM insurance_creation) = 1;'},
    {"question": "Who is the broker with the most assigned cases?",
    "expected_sql": 'SELECT brocker FROM cases GROUP BY brocker ORDER BY COUNT(*) DESC LIMIT 1;'},
    {"question": "What is the most frequent activity in the database?",
    "expected_sql": 'SELECT name FROM activity GROUP BY name ORDER BY COUNT(*) DESC LIMIT 1;'},
    {"question": "What is the total insurance value for each type of 'ramo'?",
    "expected_sql": 'SELECT ramo, SUM(value) FROM cases GROUP BY ramo;'},
    {"question": "On average, how long does it take for an insurance policy to be approved?",
    "expected_sql": 'SELECT AVG(EXTRACT(DAY FROM insurance_start - insurance_creation)) FROM cases WHERE approved = 1;'},
    {"question": "What is the average number of activities per case?",
    "expected_sql": 'SELECT COUNT(activity.id) / COUNT(DISTINCT cases.id) FROM activity INNER JOIN cases ON activity.case = cases.id;'},
    {"question": "What is the most frequent activity performed in approved cases?",
    "expected_sql": 'SELECT activity.name FROM activity INNER JOIN cases ON activity.case = cases.id WHERE cases.approved = TRUE GROUP BY activity.name ORDER BY COUNT(activity.id) DESC LIMIT 1;'},
    {"question": "What is the total duration of all activities for each case?",
    "expected_sql": 'SELECT activity.case, SUM(activity.tpt) FROM activity GROUP BY activity.case;'},
    {"question": "What is the total value of cases that have at least one recorded activity?",
    "expected_sql": 'SELECT SUM(cases.value) FROM cases WHERE cases.id IN (SELECT DISTINCT case FROM activity);'}
]

In [13]:
import time
import pandas as pd

def time_query_generation(state):
    """
    Measures the execution time of the model generating an SQL query.

    Args:
        state (dict): The state object that stores the query and result.

    Returns:
        dict: Updated state containing the query, execution time, and SQL output.
    """
    start_time = time.time()
    try:
        convert_nl_to_sql(state)  # Generates SQL query
        execute_sql(state)  # Executes SQL query
    except Exception as e:
        state["sql_query"] = f"Error: {e}"

    execution_time = time.time() - start_time
    state["execution_time"] = execution_time
    return state

In [14]:
results = []

# Run tests
for test in test_cases:
    state = {"question": test["question"], "expected_sql": test["expected_sql"],"db_conn":db_conn}
    result_state = time_query_generation(state)
    
    results.append({
        "Question": test["question"],
        "Expected SQL Query": test["expected_sql"],
        "Generated SQL Query": result_state['sql_query'],
        "Query Result": result_state["query_result"],
        "Execution Time (s)": result_state["execution_time"]
    })

# Convert results to DataFrame
df_results = pd.DataFrame(results)

Converting question to SQL How many cases are there in total in the database?
Generated SQL query: SELECT COUNT(*) AS total_cases FROM cases;
Executing SQL query: SELECT COUNT(*) AS total_cases FROM cases;
SQL SELECT query executed successfully.
total_cases: 1000
Converting question to SQL How many activities have been recorded?
Generated SQL query: SELECT COUNT(a.id) AS number_of_activities FROM activity a;
Executing SQL query: SELECT COUNT(a.id) AS number_of_activities FROM activity a;
SQL SELECT query executed successfully.
number_of_activities: 23233
Converting question to SQL What are the different types of insurance available?
Generated SQL query: SELECT DISTINCT c.type FROM cases AS c;
Executing SQL query: SELECT DISTINCT c.type FROM cases AS c;
SQL SELECT query executed successfully.
type: Renewal
type: Policy onboarding
type: Issuance
Converting question to SQL What is the total value of approved insurance policies?
Generated SQL query: SELECT SUM(c.value) AS total_value FROM cases c WHERE c.approved = TRUE;
Executing SQL query: SELECT SUM(c.value) AS total_value FROM cases c WHERE c.approved = TRUE;
SQL SELECT query executed successfully.
total_value: 3751100
Converting question to SQL How many cases were created in January?
Generated SQL query: SELECT COUNT(*) FROM cases WHERE EXTRACT(MONTH FROM insurance_creation) = 1;
Executing SQL query: SELECT COUNT(*) FROM cases WHERE EXTRACT(MONTH FROM insurance_creation) = 1;
SQL SELECT query executed successfully.
count_star(): 355
Converting question to SQL Who is the broker with the most assigned cases?
Generated SQL query: SELECT c.broker FROM cases c GROUP BY c.broker ORDER BY COUNT(c.id) DESC LIMIT 1;
Executing SQL query: SELECT c.broker FROM cases c GROUP BY c.broker ORDER BY COUNT(c.id) DESC LIMIT 1;
SQL SELECT query executed successfully.
broker: Stanley
Converting question to SQL What is the most frequent activity in the database?
Generated SQL query: SELECT a."name" FROM "activity" AS a GROUP BY a."name" ORDER BY COUNT(a."id") DESC LIMIT 1;
Executing SQL query: SELECT a."name" FROM "activity" AS a GROUP BY a."name" ORDER BY COUNT(a."id") DESC LIMIT 1;
SQL SELECT query executed successfully.
name: Enviar a Revisión suscripción
Converting question to SQL What is the total insurance value for each type of 'ramo'?
Generated SQL query: SELECT c.type, SUM(c.value) AS total_value FROM cases c WHERE c.ramo IS NOT NULL GROUP BY c.type;
Executing SQL query: SELECT c.type, SUM(c.value) AS total_value FROM cases c WHERE c.ramo IS NOT NULL GROUP BY c.type;
SQL SELECT query executed successfully.
type: Renewal, total_value: 1653800
type: Issuance, total_value: 1775000
type: Policy onboarding, total_value: 1973600
Converting question to SQL On average, how long does it take for an insurance policy to be approved?
Generated SQL query: SELECT AVG(c.avg_time) AS average_approval_duration FROM cases c WHERE c.state = 'approved';
Executing SQL query: SELECT AVG(c.avg_time) AS average_approval_duration FROM cases c WHERE c.state = 'approved';
SQL SELECT query executed successfully.
average_approval_duration: None
Converting question to SQL What is the average number of activities per case?
Generated SQL query: SELECT AVG(a.tpt) AS average_duration FROM activity a JOIN cases c ON a.case = c.id;
Executing SQL query: SELECT AVG(a.tpt) AS average_duration FROM activity a JOIN cases c ON a.case = c.id;
SQL SELECT query executed successfully.
average_duration: 41251.31744432784
Converting question to SQL What is the most frequent activity performed in approved cases?
Generated SQL query: SELECT a."name", COUNT(*) AS frequency FROM activity a JOIN cases c ON a.case = c.id WHERE c.approved = TRUE GROUP BY a."name" ORDER BY frequency DESC LIMIT 1;
Executing SQL query: SELECT a."name", COUNT(*) AS frequency FROM activity a JOIN cases c ON a.case = c.id WHERE c.approved = TRUE GROUP BY a."name" ORDER BY frequency DESC LIMIT 1;
SQL SELECT query executed successfully.
name: Revisión en emisión, frequency: 1112
Converting question to SQL What is the total duration of all activities for each case?
Generated SQL query: SELECT c.id, SUM(a.tpt) AS total_duration FROM cases AS c JOIN activity AS a ON c.id = a.case GROUP BY c.id;
Executing SQL query: SELECT c.id, SUM(a.tpt) AS total_duration FROM cases AS c JOIN activity AS a ON c.id = a.case GROUP BY c.id;
SQL SELECT query executed successfully.
id: 4549, total_duration: 324401.773704
id: 6681, total_duration: 269664.127623
id: 5212, total_duration: 348724.94665199996
id: 8954, total_duration: 1258618.5769159999
id: 3325, total_duration: 1939603.3947179997
id: 3637, total_duration: 909153.3916660001
id: 8506, total_duration: 1627200.5538160002
id: 6789, total_duration: 336079.246813
id: 1142, total_duration: 841508.8719020002
id: 2668, total_duration: 932086.698893
id: 1342, total_duration: 1373830.8009970004
id: 191, total_duration: 1978977.206891
id: 8244, total_duration: 1526273.7459049998
id: 2068, total_duration: 1359496.211848
id: 9793, total_duration: 141923.85263799998
id: 9095, total_duration: 291537.27215599996
id: 7329, total_duration: 1730067.2963319998
id: 7803, total_duration: 829688.169558
id: 4912, total_duration: 385405.766569
id: 2910, total_duration: 281904.02526799997
id: 2021, total_duration: 223208.433233
id: 7360, total_duration: 1128723.198509
id: 5133, total_duration: 821209.550059
id: 8968, total_duration: 705480.419048
id: 3110, total_duration: 1824226.6973150002
id: 7032, total_duration: 1032347.4368609999
id: 7303, total_duration: 121174.96155800001
id: 7494, total_duration: 875057.753958
id: 829, total_duration: 268392.986441
id: 6041, total_duration: 775100.3924809999
id: 7850, total_duration: 809835.9783729998
id: 5345, total_duration: 1066685.567331
id: 4725, total_duration: 715324.693202
id: 3920, total_duration: 722084.863227
id: 2597, total_duration: 292870.70204500004
id: 3471, total_duration: 852604.930044
id: 5355, total_duration: 1448991.9640099998
id: 3859, total_duration: 2044476.1642680007
id: 6245, total_duration: 1169187.647182
id: 8605, total_duration: 196748.063485
id: 6219, total_duration: 575380.347025
id: 979, total_duration: 2090330.647792
id: 9719, total_duration: 471889.326704
id: 5447, total_duration: 1068592.2428249998
id: 6204, total_duration: 244232.39870299998
id: 6249, total_duration: 779067.3172050002
id: 4821, total_duration: 245465.866365
id: 4666, total_duration: 1115884.4223389998
id: 8169, total_duration: 1135293.3453409995
id: 2439, total_duration: 790443.8159259999
id: 8579, total_duration: 1795278.7687559999
id: 822, total_duration: 1200127.5029830001
id: 9143, total_duration: 1266854.116816
id: 2513, total_duration: 1130357.1301370002
id: 1156, total_duration: 808415.3603310001
id: 4752, total_duration: 1073345.8096330003
id: 1679, total_duration: 188929.202451
id: 6865, total_duration: 1161636.165021
id: 1659, total_duration: 982766.9119060002
id: 2281, total_duration: 1431057.389308
id: 6032, total_duration: 202922.80176300002
id: 810, total_duration: 1160644.4372470004
id: 5708, total_duration: 752267.556006
id: 6266, total_duration: 785619.807113
id: 762, total_duration: 1129727.5714589998
id: 9313, total_duration: 140168.35961900002
id: 9782, total_duration: 469216.64067900006
id: 8329, total_duration: 187121.960383
id: 9488, total_duration: 100616.052543
id: 7711, total_duration: 1684147.6844350006
id: 2631, total_duration: 256681.975508
id: 8524, total_duration: 1812713.8977599996
id: 8665, total_duration: 142294.22158700004
id: 984, total_duration: 381557.54310300003
id: 9539, total_duration: 832929.9435600002
id: 6387, total_duration: 952918.74319
id: 1353, total_duration: 793249.4869049999
id: 9992, total_duration: 208772.225075
id: 6211, total_duration: 579628.0126090001
id: 3341, total_duration: 347582.06245699996
id: 3562, total_duration: 658819.244109
id: 3897, total_duration: 211403.241154
id: 950, total_duration: 1210497.9861350001
id: 2040, total_duration: 242071.25953900002
id: 5836, total_duration: 769048.3373950002
id: 1812, total_duration: 1861171.9270500003
id: 6049, total_duration: 430600.757364
id: 5036, total_duration: 1343939.186592
id: 1313, total_duration: 113156.475748
id: 9757, total_duration: 917633.1974259999
id: 9941, total_duration: 237022.75388700003
id: 9398, total_duration: 148870.062019
id: 8928, total_duration: 1564466.7749589998
id: 4313, total_duration: 807288.2246799999
id: 5437, total_duration: 936335.94464
id: 3373, total_duration: 538390.464178
id: 7883, total_duration: 1299905.827981
id: 1595, total_duration: 1098752.9690379999
id: 4805, total_duration: 1100868.7193250002
id: 4933, total_duration: 1672098.2297170002
id: 586, total_duration: 1021810.2964959999
id: 7347, total_duration: 194858.768107
id: 5097, total_duration: 1022482.0563870001
id: 1859, total_duration: 215308.313161
id: 1451, total_duration: 762269.895308
id: 4011, total_duration: 919284.9915290002
id: 9209, total_duration: 1174592.931817
id: 5747, total_duration: 897704.801335
id: 2192, total_duration: 833504.9089139999
id: 4107, total_duration: 806797.4603570001
id: 1391, total_duration: 1333438.734831
id: 5244, total_duration: 842679.0753229999
id: 697, total_duration: 1065678.894252
id: 8118, total_duration: 814362.8341330001
id: 5797, total_duration: 1118870.319216
id: 2842, total_duration: 173710.911034
id: 2144, total_duration: 1259660.949669
id: 1732, total_duration: 1682303.728007
id: 3750, total_duration: 1171329.0915920003
id: 8180, total_duration: 1049532.3697699998
id: 6739, total_duration: 447855.88821500004
id: 8830, total_duration: 139923.39428900002
id: 9354, total_duration: 238770.97811700002
id: 8917, total_duration: 1194585.7638
id: 9830, total_duration: 327800.880695
id: 3893, total_duration: 1195308.7572469998
id: 2640, total_duration: 3137680.7971610003
id: 5632, total_duration: 373978.519798
id: 1448, total_duration: 1257763.7387590003
id: 637, total_duration: 223791.28032700001
id: 8949, total_duration: 1762035.8034219996
id: 811, total_duration: 282395.143034
id: 5076, total_duration: 286203.32871699997
id: 7402, total_duration: 560032.1252209999
id: 8240, total_duration: 1663338.955484
id: 481, total_duration: 1190243.460445
id: 9294, total_duration: 532131.14278
id: 3314, total_duration: 1791007.285418
id: 9348, total_duration: 808611.2245540001
id: 4457, total_duration: 944080.2083840002
id: 7004, total_duration: 965877.0921709999
id: 2849, total_duration: 1082514.1201540004
id: 7713, total_duration: 1099549.2545260002
id: 5697, total_duration: 162556.939173
id: 196, total_duration: 1820701.909474
id: 398, total_duration: 945458.7931710001
id: 690, total_duration: 308453.671293
id: 4433, total_duration: 799934.5146519999
id: 9179, total_duration: 243759.585751
id: 308, total_duration: 1196326.7552929998
id: 6349, total_duration: 1901357.6187929998
id: 1348, total_duration: 1168269.065784
id: 1354, total_duration: 1054803.9078960002
id: 5500, total_duration: 1168299.4253600002
id: 1144, total_duration: 1338527.215938
id: 9553, total_duration: 1288205.058156
id: 3355, total_duration: 494191.96631100005
id: 3028, total_duration: 1106782.1011210002
id: 2367, total_duration: 514613.230431
id: 9778, total_duration: 857641.362715
id: 3060, total_duration: 1221457.640567
id: 4152, total_duration: 470663.92677300004
id: 7207, total_duration: 383193.87360100006
id: 9193, total_duration: 1453494.8508590003
id: 6059, total_duration: 1069320.7090390003
id: 8798, total_duration: 2497488.244809999
id: 4497, total_duration: 2514086.739095
id: 7629, total_duration: 152984.46697399998
id: 3438, total_duration: 433847.300719
id: 8818, total_duration: 271061.582905
id: 7175, total_duration: 1347955.9954269999
id: 665, total_duration: 2096468.1262540005
id: 9659, total_duration: 1139596.6380079999
id: 5511, total_duration: 1923730.2800050003
id: 7271, total_duration: 1108731.472671
id: 5066, total_duration: 1830249.5694710002
id: 6629, total_duration: 342491.128704
id: 9837, total_duration: 198247.171893
id: 4365, total_duration: 1106997.4152829999
id: 8921, total_duration: 620180.940748
id: 9318, total_duration: 4103536.230713001
id: 478, total_duration: 2301024.1651050006
id: 7474, total_duration: 974231.967414
id: 3369, total_duration: 989847.5435429999
id: 3967, total_duration: 3025333.5611659996
id: 4135, total_duration: 566834.870218
id: 3128, total_duration: 162766.820591
id: 2181, total_duration: 732662.130645
id: 5199, total_duration: 122432.165533
id: 3391, total_duration: 1138467.4545089998
id: 1205, total_duration: 2327883.8597800005
id: 8570, total_duration: 246965.89666199998
id: 9930, total_duration: 888986.024189
id: 8228, total_duration: 108330.452585
id: 7726, total_duration: 1524234.4261430001
id: 3765, total_duration: 236141.330054
id: 9557, total_duration: 959231.959465
id: 6193, total_duration: 878107.1318450001
id: 5219, total_duration: 1179666.903908
id: 4437, total_duration: 1374774.8956139998
id: 4750, total_duration: 968259.7857240001
id: 3426, total_duration: 1577002.2847269997
id: 6098, total_duration: 992171.0221380002
id: 5892, total_duration: 1951124.6305629998
id: 3255, total_duration: 276370.132202
id: 9752, total_duration: 753498.949899
id: 6075, total_duration: 626679.94246
id: 4547, total_duration: 1366628.580997
id: 9977, total_duration: 1533623.5679809996
id: 208, total_duration: 167622.262573
id: 5193, total_duration: 1267007.167507
id: 3404, total_duration: 2237975.225922
id: 8801, total_duration: 1786398.8111519997
id: 5541, total_duration: 285292.597053
id: 261, total_duration: 919243.384326
id: 9287, total_duration: 832656.516155
id: 1980, total_duration: 1950745.995995
id: 3788, total_duration: 846600.195352
id: 3466, total_duration: 724185.54685
id: 305, total_duration: 713166.2588749998
id: 757, total_duration: 1025693.7092399999
id: 1764, total_duration: 2341180.7962389993
id: 4328, total_duration: 1786477.6993699998
id: 7192, total_duration: 1147801.614089
id: 9090, total_duration: 262242.96825499996
id: 2066, total_duration: 3016088.422405998
id: 5880, total_duration: 627508.796421
id: 5240, total_duration: 384375.2146470001
id: 4788, total_duration: 1858417.0063220004
id: 4402, total_duration: 880319.1430849999
id: 9713, total_duration: 2546302.6265509995
id: 1973, total_duration: 2024095.243178999
id: 3843, total_duration: 144316.09316999998
id: 9200, total_duration: 882200.151625
id: 4274, total_duration: 1167502.650899
id: 4369, total_duration: 2282516.887577
id: 89, total_duration: 1769991.891075
id: 5290, total_duration: 344340.362484
id: 5145, total_duration: 948455.351659
id: 8186, total_duration: 1773467.5187889999
id: 4461, total_duration: 1212386.3221759999
id: 7148, total_duration: 323011.911594
id: 2300, total_duration: 749127.7429270002
id: 3301, total_duration: 834502.580374
id: 6782, total_duration: 400542.579013
id: 6826, total_duration: 1385560.7588429998
id: 2446, total_duration: 2261734.6208470003
id: 9111, total_duration: 1220838.373489
id: 3378, total_duration: 212051.659609
id: 1361, total_duration: 996463.2745660001
id: 3884, total_duration: 1213191.686058
id: 9954, total_duration: 1364420.625062
id: 573, total_duration: 1657792.2116110001
id: 4077, total_duration: 780055.942278
id: 7721, total_duration: 1074089.92817
id: 5289, total_duration: 344873.243874
id: 812, total_duration: 643058.7530990002
id: 1434, total_duration: 1443503.5919789998
id: 5078, total_duration: 209329.195322
id: 7603, total_duration: 1250221.410366
id: 1875, total_duration: 221053.085421
id: 3693, total_duration: 992892.3216679998
id: 1896, total_duration: 958368.8040659999
id: 3254, total_duration: 907641.376147
id: 9190, total_duration: 1672396.4714859999
id: 9170, total_duration: 890717.9806839998
id: 3497, total_duration: 205538.73490000004
id: 8000, total_duration: 442073.627465
id: 3140, total_duration: 702874.1866459999
id: 5127, total_duration: 1195513.562486
id: 3866, total_duration: 491898.692949
id: 7377, total_duration: 247695.804714
id: 4023, total_duration: 299126.149161
id: 6719, total_duration: 2158701.066285
id: 756, total_duration: 217842.13728900003
id: 1890, total_duration: 1319400.109673
id: 6769, total_duration: 1256452.1783870002
id: 2388, total_duration: 655393.9093899999
id: 9729, total_duration: 242309.419007
id: 2886, total_duration: 1216327.9674739998
id: 3244, total_duration: 1148156.102562
id: 7164, total_duration: 2260360.10401
id: 2935, total_duration: 1670769.5998019997
id: 6261, total_duration: 687740.6876699999
id: 2313, total_duration: 1304404.9743350004
id: 3911, total_duration: 2852609.121495
id: 1959, total_duration: 1958831.8175080002
id: 6174, total_duration: 1891192.537191
id: 1993, total_duration: 225949.40000999998
id: 2024, total_duration: 1721685.5062380002
id: 7881, total_duration: 748846.816783
id: 8540, total_duration: 2079915.86452
id: 3309, total_duration: 1680657.5366379994
id: 5758, total_duration: 1366900.5332499999
id: 5981, total_duration: 217896.05093699996
id: 2371, total_duration: 1125992.732477
id: 5053, total_duration: 1236291.010122
id: 492, total_duration: 1242034.897579
id: 1974, total_duration: 849067.370583
id: 3558, total_duration: 341141.618346
id: 2985, total_duration: 152305.477844
id: 9384, total_duration: 2376972.288489001
id: 2397, total_duration: 1304070.997465
id: 6946, total_duration: 605196.153989
id: 5318, total_duration: 1155393.120329
id: 2539, total_duration: 782686.1106649998
id: 5912, total_duration: 1168053.6811570001
id: 6896, total_duration: 441759.698153
id: 8805, total_duration: 876871.2760279998
id: 6403, total_duration: 379419.5394959999
id: 2335, total_duration: 890251.966991
id: 7027, total_duration: 1377297.7792579997
id: 9594, total_duration: 2047572.322943
id: 7215, total_duration: 1238805.2006770002
id: 8536, total_duration: 1437274.7323950003
id: 832, total_duration: 837496.685984
id: 61, total_duration: 1137600.6085960001
id: 6767, total_duration: 120262.84088900001
id: 5186, total_duration: 829726.1648569999
id: 2679, total_duration: 1769142.0384430005
id: 8630, total_duration: 310813.36946400005
id: 7346, total_duration: 1182039.450752
id: 3760, total_duration: 1002524.2586769998
id: 6326, total_duration: 2119420.7874589995
id: 8077, total_duration: 1362159.236459
id: 9082, total_duration: 404037.39519999997
id: 3049, total_duration: 360831.717417
id: 7080, total_duration: 932238.7896779999
id: 241, total_duration: 936569.278305
id: 5673, total_duration: 1448981.7021670002
id: 5111, total_duration: 1183853.136758
id: 7659, total_duration: 1171529.384985
id: 9816, total_duration: 893839.232146
id: 5890, total_duration: 2511311.968376
id: 407, total_duration: 806606.0803520001
id: 772, total_duration: 997723.753111
id: 6285, total_duration: 713553.919033
id: 547, total_duration: 1315153.921921
id: 9877, total_duration: 1218563.025121
id: 165, total_duration: 1007358.106658
id: 9703, total_duration: 2035199.8405769998
id: 8957, total_duration: 1377154.0893009999
id: 1380, total_duration: 1362795.5217100002
id: 2351, total_duration: 1473475.5626600003
id: 9066, total_duration: 1101719.5774
id: 3070, total_duration: 178091.140235
id: 2862, total_duration: 1179834.395794
id: 1019, total_duration: 2297020.6625349997
id: 2605, total_duration: 779975.138758
id: 8722, total_duration: 198414.38562400002
id: 5182, total_duration: 161965.198502
id: 526, total_duration: 1105817.645676
id: 1128, total_duration: 757806.797808
id: 4197, total_duration: 1728213.531615
id: 9534, total_duration: 149486.982549
id: 5907, total_duration: 1307839.410216
id: 3123, total_duration: 641111.026315
id: 7963, total_duration: 544271.7245639999
id: 3565, total_duration: 1234876.4577910001
id: 9975, total_duration: 151472.09271799997
id: 4789, total_duration: 827203.149393
id: 7941, total_duration: 613922.718141
id: 1546, total_duration: 314448.516604
id: 5999, total_duration: 926895.915315
id: 1502, total_duration: 886501.826168
id: 5168, total_duration: 1662973.1695009999
id: 5353, total_duration: 1478904.8787360003

In [15]:
df_results

,Question,Expected SQL Query,Generated SQL Query,Query Result,Execution Time (s)
0,How many cases are there in total in the datab...,SELECT COUNT(*) FROM cases;,SELECT COUNT(*) AS total_cases FROM cases;,total_cases: 1000,1.204677
1,How many activities have been recorded?,SELECT COUNT(*) FROM activity;,SELECT COUNT(a.id) AS number_of_activities FRO...,number_of_activities: 23233,1.293377
2,What are the different types of insurance avai...,SELECT DISTINCT type FROM cases;,SELECT DISTINCT c.type FROM cases AS c;,type: Renewal\ntype: Policy onboarding\ntype: ...,1.266402
3,What is the total value of approved insurance ...,SELECT SUM(value) FROM cases WHERE approved = 1;,SELECT SUM(c.value) AS total_value FROM cases ...,total_value: 3751100,1.569996
4,How many cases were created in January?,SELECT COUNT(*) FROM cases WHERE EXTRACT(MONTH...,SELECT COUNT(*) FROM cases WHERE EXTRACT(MONTH...,count_star(): 355,1.580955
5,Who is the broker with the most assigned cases?,SELECT brocker FROM cases GROUP BY brocker ORD...,SELECT c.broker FROM cases c GROUP BY c.broker...,broker: Stanley,1.812650
6,What is the most frequent activity in the data...,SELECT name FROM activity GROUP BY name ORDER ...,"SELECT a.""name"" FROM ""activity"" AS a GROUP BY ...",name: Enviar a Revisión suscripción,1.913677
7,What is the total insurance value for each typ...,"SELECT ramo, SUM(value) FROM cases GROUP BY ramo;","SELECT c.type, SUM(c.value) AS total_value FRO...","type: Renewal, total_value: 1653800\ntype: Iss...",1.962923
8,"On average, how long does it take for an insur...",SELECT AVG(EXTRACT(DAY FROM insurance_start - ...,SELECT AVG(c.avg_time) AS average_approval_dur...,average_approval_duration: None,1.772107
9,What is the average number of activities per c...,SELECT COUNT(activity.id) / COUNT(DISTINCT cas...,SELECT AVG(a.tpt) AS average_duration FROM act...,average_duration: 41251.31744432784,1.723190
10,What is the most frequent activity performed i...,SELECT activity.name FROM activity INNER JOIN ...,"SELECT a.""name"", COUNT(*) AS frequency FROM ac...","name: Revisión en emisión, frequency: 1112",2.368361
11,What is the total duration of all activities f...,"SELECT activity.case, SUM(activity.tpt) FROM a...","SELECT c.id, SUM(a.tpt) AS total_duration FROM...","id: 4549, total_duration: 324401.773704\nid: 6...",2.099824
12,What is the total value of cases that have at ...,SELECT SUM(cases.value) FROM cases WHERE cases...,SELECT SUM(c.value) AS total_value FROM cases ...,total_value: 125728600,1.904027

In [16]:
df_results.to_csv("results_sqlcoder.csv", index=False)